### ISSUE TITLE
Help teams share ports of Frontend

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system-roadmap#20]
## Goal
Teams can share the ports they have made of GOV.UK Frontend into other templating languages.

## Why is this important?

A wide range of templating languages are used across government, but we only provide our components in one (Nunjucks).

We'll never have a large enough team to develop and support components in multiple templating languages, but we can help teams who have ported GOV.UK Frontend into their chosen language share their work, so that other teams can benefit from the work.

## Epics

- [x] Publish a list of ports
- [ ] Publish guidance on developing ports
- [x] Provide a method to check ports use the same markup as Frontend

**Comment by timpaul** [comment]
Currently blocked by #24

**Comment by kellylee-gds** [comment]
**End of Q2 update:**

Created [Resources and tools](https://design-system.service.gov.uk/community/resources-and-tools/) page on Design System website and published details of community built ports and resources.

Released v3.9.0 of GOV.UK Frontend which included our test fixtures meaning users can check they are using the same markup as Frontend in their custom built ports.

Due to the team being without a Content Designer we were unable to write and publish guidance on developing ports.
